import axios from "axios";
import Head from "next/head";
import Main from "../components/main";

export default function Home({data}) {

  return (
    <div>
      <Head>
        <title>صفحه اصلی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main container */}
      <Main data={data} />

    </div>
  )
}

export async function getServerSideProps(context) {

  const data = (await axios.get("/api/films")).data


  return {
      props: {
          data
      },
  };
}
