import axios from "axios";
import Head from "next/head";
import Main from "../components/main";

export default function Home({ data, films }) {

  return (
    <div>
      <Head>
        <title>صفحه اصلی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main container */}
      <Main data={data} films={films} />

    </div>
  )
}

export async function getServerSideProps(context) {

  // sliders films
  const data = (await axios.get("/api/films")).data;

  // categories films
  const getFilms = (await axios.get("/api/films/categories", { params: { type: "categories", text: "scifi" } })).data;


  return {
    props: {
      data,
      films: getFilms
    },
  };
}
